// Globalized blog content. Stored as structured blocks (rendered server-side)
// so we get real, schema-rich articles without an MDX toolchain. Zero India-
// targeted posts were migrated - these are all worldwide-relevant guides.

// Text fields support minimal inline markup, rendered by the post page:
//   [label](/internal-or-external-url)   links (external get nofollow)
//   **bold**                             strong
//   `code`                               inline code
export type Block =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "ol"; items: string[] }
  | { type: "table"; headers: string[]; rows: string[][] }
  | { type: "cta"; title: string; text: string; href: string; label: string };

export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  date: string; // ISO
  readMins: number;
  /** Animated banner (public path). */
  image: string;
  tags: string[];
  /** Internal links to relevant tools. */
  relatedTools: string[];
  body: Block[];
  faqs?: { q: string; a: string }[];
}

export const POSTS: BlogPost[] = [
  {
    slug: "compress-image-to-exact-file-size",
    image: "/blog/compress-image-to-exact-file-size.png",
    title: "How to compress an image to an exact file size (complete guide)",
    description:
      "A practical guide to hitting an exact KB target - 20 KB, 100 KB, 1 MB - without trial and error, and without uploading your photos.",
    date: "2026-01-12",
    readMins: 6,
    tags: ["compression", "guide"],
    relatedTools: ["compress-image", "compress-image-to-100kb", "resize-image"],
    body: [
      { type: "p", text: "Most compressors only give you a vague quality slider, leaving you to guess and re-export until you land near the size you need. If a form demands exactly 100 KB, that's frustrating. Here's how exact-size compression actually works - and how to do it in one shot." },
      { type: "h2", text: "Why a quality slider isn't enough" },
      { type: "p", text: "The relationship between encoder quality and file size isn't linear and depends entirely on the image's content. A flat graphic and a detailed photo at the same quality setting produce wildly different sizes. That's why 'set quality to 80%' rarely hits a specific target." },
      { type: "h2", text: "The binary-search approach" },
      { type: "p", text: "The reliable method is to binary-search the quality value: encode at a mid quality, measure the result, then move the quality up or down depending on whether you're over or under target. Repeating this about a dozen times converges to within a fraction of a KB." },
      { type: "ol", items: [
        "Start with a quality range of 5-98.",
        "Encode at the midpoint and check the size.",
        "If it's under target, push quality higher; if over, lower it.",
        "Stop once you're within ~5% under the target.",
        "If even the lowest quality is too big, downscale the dimensions and try again.",
      ] },
      { type: "h2", text: "Quality first, dimensions second" },
      { type: "p", text: "To preserve sharpness, you should exhaust the quality range before shrinking dimensions. Downscaling is a last resort used only when an image simply can't reach the target at full resolution." },
      { type: "h2", text: "Do it without uploading" },
      { type: "p", text: "All of this can run in your browser with WebAssembly codecs - no server, no upload, no limits. ShrinkTo's compressor does exactly this: pick a target like 100 KB and it hits it on the first try." },
    ],
    faqs: [
      { q: "What's the smallest size I can compress a photo to?", a: "You can go very small (e.g. 20 KB), but below a point you'll see visible quality loss as the encoder runs out of room and starts downscaling. The tool always keeps quality as high as the target allows." },
      { q: "Does compressing to an exact size upload my photo?", a: "Not with ShrinkTo - the entire process runs locally in your browser." },
    ],
  },
  {
    slug: "compress-images-without-losing-quality",
    image: "/blog/compress-images-without-losing-quality.png",
    title: "How to Compress Images Without Losing Quality (Complete 2026 Guide)",
    description:
      "Learn how to compress JPG, PNG and WebP images without losing quality. Free in-browser method, exact-KB targeting, no upload. Step-by-step 2026 guide.",
    date: "2026-07-04",
    readMins: 10,
    tags: ["compression", "guide"],
    relatedTools: ["compress-image", "resize-image", "convert-image", "heic-to-jpg"],
    body: [
      { type: "p", text: "You need a smaller image file, but every compressor you try turns your crisp photo into a blurry, blocky mess. Sound familiar? The truth is that compressing images without losing quality is entirely possible - you just need to understand what actually happens when an image shrinks, and use a tool that gives you control over the process instead of a single mystery button." },
      { type: "p", text: "In this guide, you will learn exactly how image compression works, which settings preserve quality, how to hit an exact file size like 100 KB or 200 KB, and how to compress images on any device - without uploading your photos to a stranger's server." },
      { type: "cta", title: "Compress an image right now - free, private, no upload", text: "ShrinkTo compresses JPG, PNG, WebP and AVIF to an exact KB size directly in your browser. No signup, no limits, and your files never leave your device.", href: "/compress-image", label: "Compress Image Free" },
      { type: "h2", text: "Why Image Compression Matters More Than Ever" },
      { type: "p", text: "Images are usually the heaviest thing a web page loads. According to the [HTTP Archive page weight report](https://httparchive.org/reports/page-weight), image bytes make up the largest single share of the median web page - often more than scripts, fonts and HTML combined. Every unnecessary megabyte slows your site down, burns mobile data, and costs you visitors." },
      { type: "p", text: "Beyond websites, oversized images cause everyday friction: email attachments bounce, application portals reject your upload with a \"file too large\" error, cloud storage fills up, and sending a photo album over a slow connection takes forever. A 4 MB photo straight from a phone camera can usually be compressed to 200-400 KB with no visible difference - a 90%+ reduction." },
      { type: "p", text: "The key phrase is **no visible difference**. Compression only \"ruins\" images when it is done carelessly. Done properly, the version you publish or upload looks identical to the original at normal viewing sizes." },
      { type: "h2", text: "Lossy vs Lossless Compression: What \"Losing Quality\" Actually Means" },
      { type: "p", text: "Every image compressor uses one of two approaches, and understanding the difference is the foundation of quality-safe compression." },
      { type: "h3", text: "Lossless Compression" },
      { type: "p", text: "Lossless compression rearranges and encodes the image data more efficiently without discarding any of it. When you decompress the file, you get back every pixel exactly as it was. PNG optimization is the classic example. The trade-off: savings are modest, typically 10-40%, because no information is thrown away." },
      { type: "h3", text: "Lossy Compression" },
      { type: "p", text: "Lossy compression permanently removes data your eyes are least likely to notice - subtle color variations, fine noise, high-frequency detail. JPEG, WebP and AVIF are primarily lossy formats. The savings are dramatic (70-95% is normal), and at sensible quality settings the removed data is genuinely invisible in ordinary viewing." },
      { type: "h3", text: "The \"Visually Lossless\" Sweet Spot" },
      { type: "p", text: "Quality loss is not on/off - it is a dial. At JPEG quality 90+, almost nothing is discarded. Between roughly 75 and 85, files shrink dramatically while remaining indistinguishable from the original to the human eye. Below about 60, artifacts like blocking and color banding start to appear. \"Compressing without losing quality\" really means staying in that visually lossless zone - and a good tool finds it for you automatically." },
      { type: "p", text: "Worth knowing: quality numbers are not standardized between tools - \"quality 80\" in one encoder is not quality 80 in another. Modern encoders such as MozJPEG also squeeze noticeably more out of the same setting than the decades-old encoders built into many apps, which is why results vary so much from tool to tool." },
      { type: "h2", text: "What Actually Determines an Image's File Size" },
      { type: "p", text: "Four factors control how big an image file is. Adjusting the right one, in the right order, is how professionals get tiny files that still look sharp." },
      { type: "p", text: "**1. Pixel dimensions.** A 6000×4000 photo has 24 million pixels; a 1600×1067 version has 1.7 million. Resizing dimensions is the single most powerful lever. If an image will be displayed at 800 px wide, storing it at 6000 px wide wastes enormous space for zero visible benefit. Use a [resize image tool](/resize-image) first when the original is far larger than needed." },
      { type: "p", text: "**2. Format.** The same photo saved as PNG might be 5× larger than as JPEG, and a modern format like WebP or AVIF can cut another 25-50% on top of JPEG. Choosing the right format is free savings. (We compare all four in our [JPEG vs PNG vs WebP vs AVIF guide](/blog/jpeg-vs-png-vs-webp-vs-avif).)" },
      { type: "p", text: "**3. Quality setting.** The encoder's quality level controls how aggressively lossy compression discards detail. This is the fine-tuning dial." },
      { type: "p", text: "**4. Metadata.** Photos carry hidden EXIF data - camera model, GPS location, thumbnails - that can add hundreds of kilobytes. Stripping it shrinks files and protects your privacy." },
      { type: "h2", text: "How Much Space Can You Actually Save? A Real Example" },
      { type: "p", text: "Take a typical smartphone photo: 4000×3000 pixels, saved by the camera as a 4.2 MB JPEG. Suppose it is destined for a blog post displayed 1600 pixels wide. Resizing to 1600×1200 alone drops it to roughly 700 KB - same sharpness on screen, 83% smaller. Re-encoding that resized image at visually lossless quality brings it to around 250 KB. Switching the output to WebP lands near 180 KB, and AVIF closer to 130 KB." },
      { type: "p", text: "That is a 4.2 MB original arriving at ~130-250 KB - a 94-97% reduction - with no difference a reader could ever spot. Multiply that across a photo gallery, a product catalog or a year of blog posts, and careless image handling versus careful compression is the difference between a sluggish site and a fast one. The workflow that produced those numbers is exactly what follows." },
      { type: "h2", text: "How to Compress an Image Without Losing Quality (Step by Step)" },
      { type: "p", text: "Here is the fastest quality-safe workflow, using ShrinkTo's free [image compressor](/compress-image). Everything runs locally in your browser using WebAssembly codecs, so nothing is uploaded anywhere." },
      { type: "p", text: "**Step 1 - Drop in your images.** Drag and drop, paste with Ctrl/⌘+V, or browse files. You can batch as many images as you like: JPG, PNG, WebP, AVIF, and even HEIC photos from iPhones." },
      { type: "p", text: "**Step 2 - Pick a target.** Choose a preset (20 KB, 50 KB, 100 KB, 200 KB, 500 KB, 1 MB) or type a custom KB value. If you don't need an exact size, the default settings aim for maximum savings at visually lossless quality." },
      { type: "p", text: "**Step 3 - Choose an output format (optional).** \"Auto\" picks the best format for each image. Selecting WebP or AVIF usually produces the smallest files; JPEG maximizes compatibility with older systems." },
      { type: "p", text: "**Step 4 - Download.** Grab a single image or a ZIP of the whole batch. Compare the result side by side with your original - at normal zoom you should see no difference." },
      { type: "p", text: "**Step 5 - Verify the size.** The output lands within a few percent of your target, so a \"max 100 KB\" upload portal will accept it on the first try." },
      { type: "p", text: "**Pro tip:** keep your originals. Compression for a specific purpose - web, email, an upload - should always produce a copy, never overwrite the master file. Storage is cheap; a lost original is gone forever. This habit also lets you re-compress from full quality whenever a new requirement appears, instead of compressing an already-compressed file." },
      { type: "h2", text: "Recommended Settings by Use Case" },
      { type: "p", text: "Different jobs tolerate different levels of compression. Use this table as your cheat sheet:" },
      { type: "table", headers: ["Use Case", "Best Format", "Target Size", "Quality Notes"], rows: [
        ["Website hero / blog photo", "WebP or AVIF", "100-300 KB", "Resize to display width first (max ~1600-2000 px)"],
        ["E-commerce product image", "WebP", "50-150 KB", "Keep detail high; buyers zoom in"],
        ["Form / portal upload", "JPEG", "20-100 KB (as required)", "Use exact-KB targeting to pass validation first try"],
        ["Email attachment", "JPEG", "200-500 KB each", "Recipients on any device can open JPEG"],
        ["Screenshot / UI image", "PNG or WebP", "50-200 KB", "Lossless keeps text edges crisp"],
        ["Archival / print master", "Original / PNG", "No target", "Keep an uncompressed master; compress copies"],
      ] },
      { type: "cta", title: "Need an exact size like 100 KB or 50 KB?", text: "ShrinkTo runs a smart search on encoder quality until your image lands within a few percent of the target - something quality sliders simply can't do.", href: "/compress-image", label: "Try Exact-KB Compression" },
      { type: "h2", text: "How to Compress an Image to an Exact Size (20 KB, 50 KB, 100 KB)" },
      { type: "p", text: "Millions of searches every month are people trying to hit a specific file size: a job portal that demands photos under 50 KB, a government application that caps documents at 100 KB, a signature upload limited to 20 KB. Traditional tools make this painful - you drag a quality slider, export, check the size, and repeat five times." },
      { type: "p", text: "The better approach is target-based compression. Instead of guessing at quality levels, you tell the tool the size you need, and it performs a binary search on encoder quality (downscaling only if truly necessary) until the output matches your target. ShrinkTo lands within about 5% of the number you type, on the first attempt." },
      { type: "p", text: "Two tips for very small targets: first, reduce pixel dimensions before compressing - a 400×500 px photo reaches 20 KB looking far better than a 4000×5000 px one forced down to the same size. Second, prefer JPEG or WebP for small photo targets; PNG cannot compete on photographic content at tiny sizes." },
      { type: "p", text: "Application portals also love pairing requirements - a photo under 50 KB **and** a signature under 20 KB, each with its own dimension rules. Batch both files with their own targets in one session, and aim a touch under the stated cap (say 45 KB for a 50 KB limit) so a byte or two of metadata never pushes you over. One pass, both files accepted, deadline survived." },
      { type: "h2", text: "Compressing Images on Any Device" },
      { type: "h3", text: "On Windows and Mac" },
      { type: "p", text: "Windows Photos can resize images (right-click → resize), and Mac Preview offers a quality slider under File → Export. Both work for one-off jobs, but neither targets an exact KB size, handles batches gracefully, or outputs modern formats like WebP and AVIF. A browser-based tool covers all of that with nothing to install - and because ShrinkTo runs entirely on your machine, it works the same on both operating systems." },
      { type: "h3", text: "On iPhone and Android" },
      { type: "p", text: "Phones are where oversized images are born - a modern phone photo is easily 3-8 MB, and iPhones save in HEIC format that many websites reject. Open ShrinkTo in your mobile browser, and you can compress or [convert HEIC to JPG](/heic-to-jpg) on the spot. Since processing happens on the device itself, it even works well on modest connections - the only data that moves is the page itself, never your photos." },
      { type: "p", text: "Two mobile-specific bonuses. First, batching: select a whole set of vacation photos at once and compress them together before sharing, instead of letting a messaging app mangle them one by one with its own aggressive recompression. Second, privacy: phone photos embed EXIF metadata, often including GPS coordinates of exactly where the picture was taken. Compression that strips metadata removes that location trail before the image ever reaches a portal, marketplace listing or social feed." },
      { type: "h2", text: "5 Mistakes That Destroy Image Quality" },
      { type: "p", text: "**1. Recompressing a JPEG over and over.** Each lossy save discards more data. Editing and re-saving a JPEG ten times visibly degrades it. Keep an original master and always compress from that." },
      { type: "p", text: "**2. Using PNG for photographs.** PNG is lossless, which sounds like \"better quality\" - but for photos it just means a file 5-10× larger than an identical-looking JPEG or WebP. Save PNG for graphics, screenshots and transparency." },
      { type: "p", text: "**3. Compressing before cropping or resizing.** Do destructive edits first, compression last. Compressing, then enlarging or heavily editing, amplifies artifacts." },
      { type: "p", text: "**4. Choosing extreme quality settings blindly.** Quality 40 will look bad; quality 100 wastes space with no visible gain. Let a target-based tool find the balance, or stay in the 75-85 range." },
      { type: "p", text: "**5. Ignoring dimensions entirely.** No quality setting can rescue the file size of a needlessly huge image. Match dimensions to how the image will actually be displayed." },
      { type: "h2", text: "Smaller Images = Faster Sites = Better Rankings" },
      { type: "p", text: "If you run a website, compression is not just housekeeping - it directly affects Google's [Core Web Vitals](https://web.dev/articles/vitals). Largest Contentful Paint (LCP), the metric that measures how fast your main content appears, should occur within 2.5 seconds - and the LCP element is very often a hero image. Cutting that image from 2 MB to 150 KB is frequently the single biggest LCP win available, improving user experience, conversion rates and search performance at the same time. Once your images are lean, apply the same discipline to documents with our guide to [compressing PDFs to an exact size](/blog/compress-pdf-to-100kb)." },
      { type: "cta", title: "Ready to shrink your images the private way?", text: "Unlimited images, exact-KB targeting, WebP & AVIF output, and 100% in-browser processing. Open your Network tab and watch - nothing ever uploads.", href: "/compress-image", label: "Compress Images Free - No Upload" },
    ],
    faqs: [
      { q: "Does compressing an image always reduce its quality?", a: "No. Lossless compression reduces file size with zero quality change. Lossy compression does discard data, but at moderate settings (roughly JPEG quality 75-85) the difference is invisible at normal viewing sizes. Quality only visibly suffers when compression is pushed to extremes or applied repeatedly to the same file." },
      { q: "How do I compress an image to exactly 100 KB without losing quality?", a: "Use a tool with exact-size targeting. Upload your image to ShrinkTo's compressor, type 100 KB (or tap the preset), and it automatically finds the highest quality that fits your target. For best results, resize very large images to sensible dimensions first - a smaller canvas reaches 100 KB with far more detail intact." },
      { q: "What is the best image format for small file sizes?", a: "AVIF produces the smallest files, often up to 50% smaller than an equivalent JPEG, with WebP close behind at roughly 25-35% savings. JPEG remains the compatibility king for email and older systems. For photos, avoid PNG - it is designed for graphics and transparency, not photographic compression." },
      { q: "Is it safe to compress private photos with an online tool?", a: "It depends on the tool. Most online compressors upload your files to their servers for processing. ShrinkTo is different: compression happens entirely in your browser using WebAssembly, so your photos never leave your device - you can verify this by watching the Network tab in your browser's developer tools stay empty." },
      { q: "How much can I compress an image before quality loss becomes visible?", a: "A typical smartphone photo (3-8 MB) can usually be reduced by 80-95% before differences become noticeable at normal size. The safe floor depends on dimensions and content: detailed photos tolerate less compression than smooth graphics. Compress to your needed size, then compare side by side - if you can't spot the difference, you haven't lost anything that matters." },
      { q: "Can I compress multiple images at once for free?", a: "Yes. ShrinkTo has no daily cap, no per-file size ceiling and no signup requirement. Drop in an entire folder of images, set one target, and download the results as a single ZIP. Because your own device does the processing, there is no server cost to recover - which is why it stays free and unlimited." },
    ],
  },
  {
    slug: "compress-pdf-to-100kb",
    image: "/blog/compress-pdf-to-100kb.png",
    title: "How to Compress a PDF to 100 KB or Less (Free, No Upload)",
    description:
      "Compress a PDF to 100 KB, 200 KB or any exact size for free. Works in your browser with no upload - perfect for job portals, forms and email. Step-by-step.",
    date: "2026-07-01",
    readMins: 10,
    tags: ["pdf", "guide"],
    relatedTools: ["compress-pdf", "split-pdf", "scan-to-pdf", "unlock-pdf"],
    body: [
      { type: "p", text: "\"File size must not exceed 100 KB.\" If you have ever applied for a job, submitted a government form, or uploaded documents to a university portal, you have met this error message - usually five minutes before a deadline. Your PDF is 2 MB, the portal wants 100 KB, and every tool you try either misses the target, slaps on a watermark, or asks you to upload your bank statement to an unknown server." },
      { type: "p", text: "This guide shows you how to compress a PDF to 100 KB, 200 KB, 500 KB or any exact size - for free, without installing software, and without your document ever leaving your device. You will also learn why PDFs get bloated in the first place, and how to shrink even stubborn scanned documents while keeping the text perfectly readable." },
      { type: "cta", title: "Compress your PDF right now - free and private", text: "ShrinkTo reduces PDF size directly in your browser. No upload, no signup, no watermarks, no limits - your documents never touch a server.", href: "/compress-pdf", label: "Compress PDF Free" },
      { type: "h2", text: "Why Do Websites Demand 100 KB or 200 KB PDFs?" },
      { type: "p", text: "Strict upload limits exist because portals handle millions of submissions. Small files keep servers fast, storage cheap, and review workflows smooth - a clerk opening 500 applications a day cannot wait on 20 MB scans. That is why recruitment portals, visa applications, bank KYC systems, university admissions and government e-services routinely cap documents somewhere between 50 KB and 500 KB." },
      { type: "p", text: "The frustrating part is that these limits are hard cut-offs: 101 KB fails just as completely as 10 MB. Guessing with a generic \"compress\" button rarely lands you under the line on the first try. Here are the limits you are most likely to run into:" },
      { type: "table", headers: ["Scenario", "Typical Limit", "Recommended Target"], rows: [
        ["Government / exam application portals", "50-300 KB per document", "Just under the stated cap (e.g. 95 KB for a 100 KB limit)"],
        ["Job applications / résumé uploads", "100 KB - 2 MB", "100-500 KB"],
        ["Email attachments (Gmail, Outlook)", "20-25 MB total", "Under 5 MB for fast sending"],
        ["University / LMS submissions", "2-10 MB", "1-2 MB"],
        ["Website downloads / brochures", "No hard limit", "Under 1 MB for good UX"],
      ] },
      { type: "p", text: "For reference, Gmail's official attachment ceiling is [25 MB including the message itself](https://support.google.com/mail/answer/6584) - but nobody enjoys receiving a 25 MB email. Smaller is always kinder." },
      { type: "h2", text: "What Makes a PDF So Large in the First Place?" },
      { type: "p", text: "A PDF containing nothing but text is remarkably small - often 30-100 KB for many pages, because text is stored as compact character data. File size explodes for four reasons:" },
      { type: "p", text: "**Images and scans.** This is the culprit 90% of the time. A single page scanned at 300 DPI in full color can weigh 1-5 MB on its own. A \"PDF\" that is really a stack of photographed pages is essentially an image album wearing a PDF costume." },
      { type: "p", text: "**High resolution beyond need.** Print work needs 300 DPI; on-screen reading is perfectly comfortable at 100-150 DPI. Storing screen documents at print resolution multiplies size for no visible benefit." },
      { type: "p", text: "**Embedded fonts.** Every embedded typeface adds data - sometimes entire font families are packed in when only a few characters are used." },
      { type: "p", text: "**Duplicate and leftover data.** Editing history, form data, thumbnails and repeated resources accumulate, especially in PDFs that have been merged or edited many times." },
      { type: "p", text: "Knowing the cause tells you the fix: compress the images inside the PDF intelligently, downsample resolution to what the use case needs, and strip the junk - which is exactly what a good compressor automates." },
      { type: "h2", text: "How to Compress a PDF to an Exact Size (Step by Step)" },
      { type: "p", text: "**Step 1 - Open the tool.** Go to ShrinkTo's [Compress PDF](/compress-pdf) page in any browser, on any device. There is nothing to install and no account to create." },
      { type: "p", text: "**Step 2 - Add your PDF.** Drag and drop the file or browse for it. Because processing happens locally in your browser, even large files load instantly - there is no upload progress bar, because there is no upload." },
      { type: "p", text: "**Step 3 - Set your target.** Choose how small the PDF needs to be - for a 100 KB portal limit, aim slightly under, around 90-95 KB, to leave a safety margin." },
      { type: "p", text: "**Step 4 - Compress and check.** The tool re-encodes the images inside your PDF at optimized quality and strips redundant data, then shows you the new size. Skim the result to confirm text is crisp and every page survived." },
      { type: "p", text: "**Step 5 - Download and upload with confidence.** Your compressed PDF is ready for the portal - first attempt, no watermark, no email required." },
      { type: "p", text: "**Tip:** keep the original file untouched and treat every compressed version as a purpose-built copy. Portals sometimes change their limits, recruiters sometimes ask for a higher-quality version later, and compressing an already-compressed PDF stacks quality loss. Compress from the original every time and you always start from full quality." },
      { type: "cta", title: "Deadline in five minutes?", text: "Skip the trial and error. Compress your PDF under any portal limit right in your browser - free, unlimited and completely private.", href: "/compress-pdf", label: "Shrink My PDF Now" },
      { type: "h2", text: "5 Ways to Reduce PDF File Size (Ranked)" },
      { type: "h3", text: "1. Use a Dedicated PDF Compressor (Best for Existing PDFs)" },
      { type: "p", text: "When the PDF already exists and you need it smaller, a purpose-built compressor gives the biggest savings with the least effort. It downsamples oversized images, re-encodes them with efficient codecs, and removes redundant objects - routinely cutting image-heavy files by 70-95% while text stays vector-sharp." },
      { type: "h3", text: "2. Rebuild the PDF from Source at Lower Image Quality" },
      { type: "p", text: "If you own the original document (Word, PowerPoint, Google Docs), re-export it with images pre-compressed. Shrinking pictures before they enter the PDF gives excellent quality control - our guide on [compressing images without losing quality](/blog/compress-images-without-losing-quality) covers the settings. The downside is that it only helps when you have the source file." },
      { type: "h3", text: "3. Remove Pages You Don't Need" },
      { type: "p", text: "Portals often need only specific pages - the certificate, not the 40-page booklet around it. [Splitting the PDF](/split-pdf) to just the required pages can beat any compression ratio, and you can always [merge PDFs](/merge-pdf) back together later." },
      { type: "h3", text: "4. Re-scan Smarter Instead of Compressing Harder" },
      { type: "p", text: "If your PDF is a scan, the scan settings matter more than any after-the-fact tool. Scan documents in grayscale (or black-and-white for pure text) at 150 DPI for digital submission, and the file starts small. Using your phone, a [scan-to-PDF tool](/scan-to-pdf) that captures directly to document mode avoids the multi-megabyte photo problem entirely." },
      { type: "h3", text: "5. Desktop Software (Adobe Acrobat and Similar)" },
      { type: "p", text: "Paid tools like [Adobe Acrobat](https://www.adobe.com/acrobat.html) include \"Reduce File Size\" and detailed PDF optimizer settings. They work well, but for the occasional compression job a subscription is overkill - and most free online alternatives quietly upload your document to their servers, which matters for sensitive files." },
      { type: "table", headers: ["Method", "Typical Savings", "Cost", "Privacy"], rows: [
        ["ShrinkTo (in-browser)", "70-95% on image-heavy PDFs", "Free, unlimited", "File never leaves your device"],
        ["Rebuild from source file", "50-90%", "Free (needs source)", "Local"],
        ["Remove / split pages", "Proportional to pages cut", "Free", "Local with ShrinkTo"],
        ["Re-scan at lower DPI / grayscale", "60-90% vs color 300 DPI", "Free", "Local"],
        ["Adobe Acrobat Pro", "50-80%", "Paid subscription", "Local (desktop app)"],
      ] },
      { type: "h2", text: "Compressing Scanned PDFs: The Special Case" },
      { type: "p", text: "Scanned documents are the hardest PDFs to shrink, because every page is one big photograph. Three levers make the difference. First, **resolution**: downsampling from 300 DPI to 150 DPI cuts image data by roughly 75% and remains fully readable on screen. Second, **color**: converting color scans of black-text documents to grayscale removes two-thirds of the channel data - and true black-and-white text scans compress smaller still. Third, **encoding**: modern JPEG encoding of scan images at quality 60-75 is visually fine for documents." },
      { type: "p", text: "A common trap is the phone-camera \"scan\": snapping a full-resolution photo of a page and converting it to PDF produces a 3-5 MB page full of shadows, background clutter and uneven lighting - the worst possible starting point. Document-mode capture instead crops to the page, flattens the perspective, boosts text contrast and outputs a fraction of the size. If your existing PDF was built from camera photos, expect to lean harder on grayscale conversion and page removal to reach tight targets." },
      { type: "p", text: "One bonus move: if your scan needs to be searchable rather than tiny, run it through an [OCR PDF tool](/ocr-pdf) - recognized text is selectable, searchable and adds almost nothing to file size. And if a portal wants images instead of documents (or vice versa), converting with [JPG to PDF](/jpg-to-pdf) keeps you covered in both directions." },
      { type: "h2", text: "Compressing PDFs for Email: The Hidden Math" },
      { type: "p", text: "Email limits are sneakier than portal limits. Gmail's 25 MB ceiling sounds generous, but attachments are encoded for transport in a way that inflates them by roughly a third - so a 20 MB PDF can bounce from a \"25 MB\" inbox. Worse, the receiving server has its own cap, and many corporate mail systems reject anything over 10 MB no matter what your provider allows." },
      { type: "p", text: "The practical rule: keep emailed PDFs under 5 MB, and under 2 MB when the recipient's setup is unknown. Compressing a 30-page proposal from 18 MB to 3 MB takes seconds, guarantees delivery, and spares the recipient a painful download on hotel Wi-Fi. For genuinely huge documents, compress first and only then fall back to a file-sharing link - a link that expires is a poor substitute for an attachment that simply arrives." },
      { type: "h2", text: "Troubleshooting: When a PDF Refuses to Shrink" },
      { type: "p", text: "Occasionally a PDF barely budges no matter what you do. The usual suspects, and their fixes:" },
      { type: "p", text: "**It's password-protected.** Encrypted files cannot be re-processed until the protection is removed. If you legitimately have the password, [unlock the PDF](/unlock-pdf) first, compress, then re-protect if needed." },
      { type: "p", text: "**It's already optimized.** A PDF exported from modern software with sensible settings has little fat left to trim. Getting it dramatically smaller now means trade-offs: lower image resolution, grayscale, or fewer pages." },
      { type: "p", text: "**It's mostly text or vector graphics.** Text and vector line-work are already compact, so image-focused compression finds nothing to squeeze. Drawings and CAD exports with millions of vector paths are the classic case - here, splitting pages helps more than compression ever will." },
      { type: "p", text: "**The limit is simply unrealistic for the content.** Ten pages of color scans will not gracefully become 50 KB. Combine tools: extract only the required pages, grayscale, compress - in that order." },
      { type: "h2", text: "How Small Is Too Small? Keeping Text Readable" },
      { type: "p", text: "Compression has a floor. A rule of thumb per A4 page for readable results: text-only pages can go below 50 KB with ease; grayscale scanned pages are comfortable around 60-150 KB; dense color pages need 100-300 KB. If a portal demands 100 KB for a 10-page color scan, compression alone may not get there gracefully - combine methods: split out the essential pages, convert to grayscale, then compress. Always open the final file at 100% zoom and confirm the smallest text is legible before submitting." },
      { type: "h2", text: "A Word on Privacy: Where Does Your PDF Actually Go?" },
      { type: "p", text: "Think about what PDFs usually contain - salary slips, ID documents, bank statements, medical records, signed contracts. Most \"free online PDF compressors\" work by uploading your file to their servers, processing it there, and (they promise) deleting it later. For sensitive documents, that is a real exposure." },
      { type: "p", text: "ShrinkTo takes the opposite approach: the compression engine runs inside your browser using WebAssembly. Your PDF is processed by your own device's CPU, and you can verify no upload happens by opening your browser's developer tools and watching the Network tab stay empty while you compress. Private by architecture, not by promise." },
      { type: "p", text: "This matters most in exactly the situations where strict size limits appear: visa applications, loan documents, KYC verification. Those are the most sensitive files most people ever handle, being pushed through compression tools under deadline pressure - the worst possible moment to skip reading a privacy policy. A tool that physically cannot receive your file removes the question entirely." },
      { type: "cta", title: "Compress sensitive PDFs without uploading them anywhere", text: "Bank statements, IDs, contracts - shrink them all in your browser. Free, no signup, no file ever sent to a server.", href: "/compress-pdf", label: "Compress PDF Privately" },
    ],
    faqs: [
      { q: "How do I compress a PDF to exactly 100 KB?", a: "Open ShrinkTo's Compress PDF tool, add your file, and compress with a target just under 100 KB (around 90-95 KB is a safe margin for strict portals). The images inside the document are re-encoded at optimized quality until the file fits. For multi-page color scans, split out only the required pages first for the best quality at that size." },
      { q: "Will compressing a PDF make the text blurry?", a: "Real text in a PDF is stored as vector data and stays razor-sharp at any compression level - only embedded images are re-encoded. If your \"text\" looks soft after compression, the document is actually a scan (a photo of text). For scans, keep resolution at 150 DPI or above and check readability at 100% zoom." },
      { q: "How can I reduce PDF size without Adobe Acrobat?", a: "You don't need paid software. A browser-based compressor handles the same image downsampling and data cleanup that Acrobat's \"Reduce File Size\" performs - free and with no installation. Alternatives include re-exporting from the source document at lower image quality or removing unneeded pages." },
      { q: "Why is my PDF still large after compression?", a: "Usually one of three reasons: the file is a high-DPI color scan (try grayscale plus a lower target), it contains many pages (split out what you need), or it was already heavily compressed, leaving little left to squeeze. Text-heavy PDFs also start small, so percentage savings look modest even when the tool is working correctly." },
      { q: "Is it safe to compress confidential PDFs online?", a: "Only if the tool processes files locally. Most online compressors upload your document to a server, which you should avoid for confidential material. ShrinkTo runs entirely in your browser - the file never leaves your device, which you can verify in your browser's Network tab while compressing." },
      { q: "Can I compress a PDF to 200 KB or 500 KB instead?", a: "Yes - the same process works for any target. Aim slightly below the portal's stated limit (for example ~190 KB for a 200 KB cap) so metadata or re-saving never tips you over. Larger targets like 500 KB preserve noticeably more image detail, so never compress further than the requirement demands." },
    ],
  },
  {
    slug: "jpeg-vs-png-vs-webp-vs-avif",
    image: "/blog/jpeg-vs-png-vs-webp-vs-avif.png",
    title: "JPEG vs PNG vs WebP vs AVIF: Which Image Format Should You Use in 2026?",
    description:
      "JPEG vs PNG vs WebP vs AVIF compared: file size, quality, transparency and browser support. Find the best image format for web, email and design in 2026.",
    date: "2026-07-02",
    readMins: 10,
    tags: ["formats", "comparison"],
    relatedTools: ["convert-image", "png-to-jpg", "compress-image", "heic-to-jpg"],
    body: [
      { type: "p", text: "Save as JPEG or PNG? Switch everything to WebP? Is AVIF ready yet? Choosing an image format feels like a technicality until you pick the wrong one - and end up with a logo full of fuzzy edges, a photo five times heavier than it should be, or an image a client's old system cannot open at all." },
      { type: "p", text: "This guide compares the four formats that matter in 2026 - JPEG, PNG, WebP and AVIF - across file size, quality, transparency, and compatibility, then gives you a simple decision rule for every common situation." },
      { type: "cta", title: "Convert between any of these formats in seconds", text: "ShrinkTo converts JPG, PNG, WebP and AVIF right in your browser - free, unlimited, and nothing is ever uploaded.", href: "/convert-image", label: "Convert an Image Free" },
      { type: "h2", text: "The Four Formats at a Glance" },
      { type: "p", text: "Before the details, here is the whole comparison in one table:" },
      { type: "table", headers: ["Feature", "JPEG", "PNG", "WebP", "AVIF"], rows: [
        ["**Compression**", "Lossy", "Lossless", "Lossy + lossless", "Lossy + lossless"],
        ["**Typical size vs JPEG**", "Baseline", "3-10× larger (photos)", "~25-35% smaller", "Up to ~50% smaller"],
        ["**Transparency**", "No", "Yes", "Yes", "Yes"],
        ["**Animation**", "No", "No (APNG rare)", "Yes", "Yes"],
        ["**Browser support**", "Universal", "Universal", "All modern browsers", "All modern browsers"],
        ["**Best for**", "Photos, email, max compatibility", "Logos, screenshots, transparency", "General web images", "Performance-critical web images"],
      ] },
      { type: "h2", text: "JPEG: The Universal Veteran" },
      { type: "p", text: "JPEG (or JPG - same format, shorter extension) has been the default photo format since the early 1990s. It uses lossy compression designed for photographic content: smooth gradients, natural textures, millions of colors. At sensible quality settings it shrinks photos dramatically while looking clean." },
      { type: "p", text: "**Strengths:** Every device, browser, email client, CMS and government portal on Earth opens JPEG. It compresses photos to small files, and modern encoders like MozJPEG squeeze it further than old ones did. When compatibility is non-negotiable, JPEG wins." },
      { type: "p", text: "**Weaknesses:** No transparency, no animation, and visible artifacts around sharp edges and text - which is why screenshots saved as JPEG look smudgy. Repeated re-saving compounds quality loss, a problem we cover in our guide to [compressing images without losing quality](/blog/compress-images-without-losing-quality)." },
      { type: "p", text: "One underused JPEG feature: progressive encoding. A progressive JPEG loads as a full-frame blurry preview that sharpens in passes, rather than painting sharply from the top down - perceived loading feels faster on slow connections, and progressive files are often slightly smaller too. Most modern encoders produce progressive output by default, but plenty of old tooling still doesn't, which is one more reason two \"identical\" JPEGs can behave differently." },
      { type: "h2", text: "PNG: The Lossless Perfectionist" },
      { type: "p", text: "PNG was created as a patent-free successor to GIF, and it remains the standard for images that must be pixel-perfect. Its compression is fully lossless: every save produces an identical image, forever." },
      { type: "p", text: "**Strengths:** True alpha transparency (soft, anti-aliased edges over any background), crisp reproduction of text, lines and flat colors, and universal support. For logos, icons, UI screenshots and diagrams, PNG is excellent." },
      { type: "p", text: "**Weaknesses:** Size - the price of losslessness. A photograph saved as PNG is routinely 3-10× larger than a visually identical JPEG, which is why \"why is my PNG so big?\" is one of the most common image questions on the internet. If you have photo PNGs bloating your site, converting [PNG to JPG](/png-to-jpg) (or better, to WebP) is the fastest fix available." },
      { type: "p", text: "PNG also comes in two flavors worth knowing. PNG-24 stores full truecolor and is what most tools export by default. PNG-8 restricts the image to a 256-color palette - dramatically smaller, and completely sufficient for flat-color graphics like simple logos, charts and icons. Smart PNG optimizers quantize colors and strip redundant chunks automatically, which is how a bloated 900 KB logo export becomes a 40 KB file with no visible change." },
      { type: "h2", text: "WebP: The Modern Web Standard" },
      { type: "p", text: "Google introduced WebP to replace both JPEG and PNG on the web, and by 2026 it has essentially succeeded. It supports lossy and lossless compression, transparency and animation in a single format." },
      { type: "p", text: "**Strengths:** According to [Google's own comparative study](https://developers.google.com/speed/webp/docs/webp_study), lossy WebP files are roughly 25-34% smaller than JPEGs of equivalent visual quality. Lossless WebP also beats PNG by a wide margin. One format handles photos, graphics and transparent images alike - simplifying entire asset pipelines." },
      { type: "p", text: "**Weaknesses:** Support outside browsers still lags: some older desktop software, email clients and upload portals reject WebP files, prompting the classic \"convert WebP to PNG/JPG\" scramble. For anything leaving the web ecosystem, keep a JPEG or PNG version handy." },
      { type: "p", text: "A bit of background explains the design: WebP grew out of the VP8 video codec, essentially treating a still image as a single high-quality video frame. That heritage is why it compresses so efficiently and why animated WebP files embarrass GIFs on size. It also explains the one place WebP is a poor citizen - print workflows and professional photo archives, where its consumer-web focus (and 8-bit color depth in lossy mode) makes TIFF or high-quality originals the better keep." },
      { type: "h2", text: "AVIF: The Compression Champion" },
      { type: "p", text: "AVIF is the newest of the four, built on the AV1 video codec. It is the current state of the art in image compression." },
      { type: "p", text: "**Strengths:** The smallest files of any mainstream format - often up to 50% lighter than an equivalent JPEG, with especially graceful handling of low-quality settings where JPEG falls apart into blocks. It supports transparency, animation, HDR and wide color gamuts. For image-heavy sites chasing Core Web Vitals, AVIF delivers the biggest wins." },
      { type: "p", text: "**Weaknesses:** Encoding is slower than WebP (a build-time cost, not a user-facing one), and like WebP, support outside modern browsers is patchy - many non-browser apps and portals don't accept it yet. Fine detail at very high quality can occasionally look slightly softer than a top-quality JPEG, though at web-typical sizes this is rarely visible." },
      { type: "p", text: "AVIF's pedigree makes its future secure: the underlying AV1 codec is developed by the Alliance for Open Media - a consortium including Google, Apple, Netflix, Amazon, Microsoft and Mozilla - and it is royalty-free by design. It is also the only format of the four with first-class 10-bit and HDR support, which is why photography-forward sites increasingly serve AVIF to modern displays. In short: AVIF is not an experiment; it is where images are heading." },
      { type: "cta", title: "Stuck with the wrong format?", text: "Turn WebP into JPG, PNG into WebP, HEIC into anything - instantly, privately, in your browser, with no upload and no signup.", href: "/convert-image", label: "Convert Image Now" },
      { type: "h2", text: "Which Format Should You Use? (Decision Guide)" },
      { type: "h3", text: "For Photographs" },
      { type: "p", text: "On the web: WebP as your workhorse, AVIF if you want maximum performance. Off the web - email attachments, portal uploads, sharing with non-technical people - use JPEG, because it opens everywhere without question. Never PNG for photos unless a spec explicitly demands it." },
      { type: "h3", text: "For Logos, Icons and Graphics With Transparency" },
      { type: "p", text: "PNG remains the safe default: universal support and perfect edges. On performance-focused websites, lossless WebP gives the same pixel-perfect result at a smaller size. JPEG is disqualified - it has no transparency and smears sharp edges." },
      { type: "h3", text: "For Screenshots and UI Images" },
      { type: "p", text: "PNG or lossless WebP. Text in screenshots turns fuzzy under JPEG's photographic compression, and documentation full of blurry screenshots looks unprofessional instantly." },
      { type: "h3", text: "For Website Performance" },
      { type: "p", text: "Serve AVIF with a WebP fallback using the HTML `<picture>` element, or simply standardize on WebP for a simpler pipeline - either approach cuts image weight enormously versus JPEG/PNG. The [MDN image format guide](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types) documents the markup patterns. Whichever format you pick, compress properly and size images to their display dimensions - format choice cannot rescue a 6000-pixel-wide hero image." },
      { type: "h3", text: "For Social Media" },
      { type: "p", text: "Upload high-quality JPEG (or PNG for graphics) at each platform's recommended dimensions and let the platform do the rest - every major network re-compresses whatever you upload with its own pipeline anyway. Uploading an already heavily compressed file means it gets compressed twice, which is where visible mushiness comes from. Give the platform the cleanest reasonable source and your posts survive its processing best." },
      { type: "h3", text: "For Email and Messaging Apps" },
      { type: "p", text: "JPEG, no contest. Recipients open attachments on ancient work laptops, old Android phones and corporate webmail - environments where WebP support is a coin flip and AVIF is a mystery file. A well-compressed JPEG in the 200-500 KB range looks great, downloads fast and opens for absolutely everyone." },
      { type: "h3", text: "For Documents and Uploads" },
      { type: "p", text: "Portals almost always specify JPEG (photos) or PDF (documents). Convert to exactly what is asked - and when a size cap applies, see our walkthrough on [compressing a PDF to 100 KB](/blog/compress-pdf-to-100kb)." },
      { type: "h2", text: "What About GIF, HEIC, SVG and TIFF?" },
      { type: "p", text: "Four other formats come up constantly, and each has a clear verdict in 2026." },
      { type: "p", text: "**GIF** survives purely on culture, not merit. Limited to 256 colors and shockingly inefficient for animation, it is beaten on every axis by animated WebP and AVIF - or by an actual short video file, which is smaller still. Use GIF only where a platform literally requires it." },
      { type: "p", text: "**HEIC** is Apple's default camera format, based on the HEVC video codec. It stores excellent quality in about half the space of JPEG, which is great on your phone and a nuisance everywhere else - endless portals and Windows machines reject it. When a website refuses your iPhone photo, a quick [HEIC to JPG conversion](/heic-to-jpg) solves it in seconds." },
      { type: "p", text: "**SVG** is not a pixel format at all - it describes shapes mathematically, so it scales to any size with zero quality loss and often weighs just a few kilobytes. For logos, icons and simple illustrations on the web, SVG beats every raster format in this article. It cannot represent photographs." },
      { type: "p", text: "**TIFF** is the archival and print heavyweight: lossless, high bit-depth, enormous. Perfect as a master file in professional workflows, absurd as anything user-facing. Export delivery copies to JPEG or WebP." },
      { type: "h2", text: "Real-World File Size Comparison" },
      { type: "p", text: "Here is what the same 1600×1067 photo looks like across formats at visually comparable quality - representative numbers you can reproduce with any typical photo:" },
      { type: "table", headers: ["Format", "Approx. Size", "vs JPEG"], rows: [
        ["PNG (lossless)", "~1.8 MB", "~6× larger"],
        ["JPEG (quality 80)", "~300 KB", "Baseline"],
        ["WebP (quality 80)", "~210 KB", "~30% smaller"],
        ["AVIF (comparable quality)", "~150 KB", "~50% smaller"],
      ] },
      { type: "p", text: "Multiply that across every image on a 50-page website and the difference between formats becomes gigabytes of bandwidth and seconds of loading time." },
      { type: "h2", text: "Browser and Device Support in 2026" },
      { type: "p", text: "The old objection to modern formats - \"but Safari can't open it\" - is history. WebP has enjoyed support across Chrome, Firefox, Safari and Edge since 2020, and AVIF completed the set when Edge added support in early 2024. Per [Can I Use](https://caniuse.com/avif), both formats now reach the overwhelming majority of global web users." },
      { type: "p", text: "The remaining gaps are outside the browser: older versions of desktop image viewers and editors, some email clients, office software and strict upload portals. The practical rule for 2026: modern formats on the web, JPEG/PNG when the file leaves the web." },
      { type: "p", text: "And if you must support genuinely ancient browsers, the web solved this years ago: the `<picture>` element lists sources in order of preference - AVIF, then WebP, then JPEG - and every browser silently picks the best one it understands. You get modern compression for the 95%+ and a safety net for the rest, with no JavaScript and no user ever seeing a broken image." },
      { type: "h2", text: "How to Convert Between Image Formats (Free)" },
      { type: "p", text: "Conversion takes seconds with ShrinkTo's [image converter](/convert-image): drop in your files (JPG, PNG, WebP, AVIF - even [iPhone HEIC photos](/heic-to-jpg)), choose the output format, and download individually or as a ZIP. You can set an exact KB target during conversion, killing two birds with one stone. Everything runs locally in your browser via WebAssembly, so batch-converting a hundred images costs you nothing and exposes your files to no one." },
      { type: "p", text: "One quality tip: when converting from a lossy source (like JPEG) to another lossy format, convert from the highest-quality version you have. And converting a JPEG to PNG does not improve its quality - it just makes the same pixels heavier; the data JPEG discarded is gone for good." },
      { type: "p", text: "For site owners, the highest-leverage move is a one-time migration: batch-convert your existing JPEG and PNG library to WebP, re-upload, and enjoy the bandwidth savings on every page view forever after. Combine the format switch with proper [compression](/compress-image) and correct dimensions, and most sites cut total image weight by well over half in an afternoon - no redesign, no plugins, no risk." },
      { type: "cta", title: "Pick the right format, then make it tiny", text: "Convert and compress in one step - exact-KB targeting, WebP & AVIF output, unlimited files, 100% in-browser.", href: "/compress-image", label: "Compress & Convert Free" },
    ],
    faqs: [
      { q: "Is WebP better than PNG?", a: "For the web, usually yes - lossless WebP reproduces the exact same pixels as PNG at a meaningfully smaller size, and lossy WebP is far smaller again when pixel-perfection isn't required. PNG still wins on compatibility outside browsers, so keep PNG for files you'll share with unknown software." },
      { q: "Should I still use JPEG in 2026?", a: "Yes, for anything that leaves the web: email attachments, documents, portal uploads and sharing with non-technical recipients. JPEG's superpower is that literally everything opens it. On your own website, though, WebP or AVIF will serve the same quality in noticeably smaller files." },
      { q: "What are the downsides of AVIF?", a: "Slower encoding, patchier support in non-browser software, and occasionally softer rendering of very fine detail at high quality settings. None of these matter for typical web images, where AVIF's ~50% size advantage over JPEG dominates - but they explain why JPEG and PNG haven't disappeared." },
      { q: "Does converting an image to another format reduce quality?", a: "Converting to a lossless format (PNG, lossless WebP) never loses quality. Converting to a lossy format (JPEG, lossy WebP/AVIF) re-encodes the image, which discards some data - invisible at good quality settings. Always convert from your best available original rather than from an already heavily compressed copy." },
      { q: "What is the best image format for a website in 2026?", a: "WebP is the best all-round choice: excellent compression, transparency, animation and full browser support. If you're chasing maximum performance, serve AVIF with WebP fallback via the picture element. Use PNG only for assets that specifically need it, and reserve JPEG for compatibility contexts." },
      { q: "How do I convert PNG to JPG without losing transparency?", a: "You can't keep transparency in JPG - the format doesn't support it, so transparent areas get flattened onto a background color (usually white). If you need transparency at a smaller size than PNG, convert to WebP or AVIF instead; both preserve full alpha transparency." },
    ],
  },
  {
    slug: "shrink-pdf-for-email-attachment-limits",
    image: "/blog/shrink-pdf-for-email-attachment-limits.png",
    title: "How to shrink a PDF for email attachment limits (Gmail, Outlook)",
    description: "Hit Gmail's 25 MB and Outlook's 20 MB limits by compressing your PDF in the browser - no upload required.",
    date: "2026-01-26",
    readMins: 5,
    tags: ["pdf", "guide"],
    relatedTools: ["compress-pdf", "compress-pdf-to-100kb", "merge-pdf"],
    body: [
      { type: "p", text: "Bounced email because your PDF is too big? Most providers cap attachments: Gmail at 25 MB, Outlook.com at around 20 MB, and many corporate mail servers far lower. Here's how to get under the line." },
      { type: "h2", text: "Why PDFs get huge" },
      { type: "p", text: "The usual culprit is images - scanned documents and PDFs full of high-resolution photos balloon in size. Text-only PDFs are almost always small." },
      { type: "h2", text: "Compress without uploading" },
      { type: "p", text: "ShrinkTo's PDF compressor re-renders pages as optimized images at a sensible resolution and quality, which dramatically reduces size for image-heavy and scanned files - all in your browser." },
      { type: "ol", items: [
        "Open the Compress PDF tool.",
        "Drop your PDF in.",
        "Choose a quality level (Balanced is a good start).",
        "Download - and check it's under your provider's limit.",
      ] },
      { type: "h2", text: "Other tricks" },
      { type: "ul", items: [
        "Split the PDF and send it in parts.",
        "Remove pages you don't need before sending.",
        "For text-only documents, make sure you're not exporting at an unnecessarily high resolution.",
      ] },
    ],
  },
  {
    slug: "browser-based-tools-are-more-private",
    image: "/blog/browser-based-tools-are-more-private.png",
    title: "Why browser-based file tools are more private than upload-based ones",
    description: "If a tool uploads your files to its servers, you've already lost control of them. Here's why in-browser tools are fundamentally more private.",
    date: "2026-02-02",
    readMins: 6,
    tags: ["privacy"],
    relatedTools: ["compress-image", "protect-pdf", "unlock-pdf"],
    body: [
      { type: "p", text: "Every time you upload a document to an online tool, a copy leaves your device and lands on someone else's computer. Even with good intentions, that introduces real risk." },
      { type: "h2", text: "The problem with upload-based tools" },
      { type: "ul", items: [
        "Your file sits on a third-party server, at least temporarily.",
        "You're trusting their retention, access, and security policies.",
        "Data in transit and at rest can be intercepted or breached.",
        "For sensitive documents - contracts, IDs, medical records - that's a lot to give up for a quick compression.",
      ] },
      { type: "h2", text: "How in-browser tools work differently" },
      { type: "p", text: "Modern browsers can run the same compression and PDF logic locally using WebAssembly. The file is read into memory on your device, processed there, and the result is handed straight back to you. Nothing is transmitted." },
      { type: "h2", text: "How to verify it" },
      { type: "p", text: "Open your browser's developer tools, switch to the Network tab, and run the tool. With a genuinely client-side tool like ShrinkTo, you'll see no upload of your file at all. It's privacy you can confirm with your own eyes." },
      { type: "h2", text: "A GDPR-friendly side effect" },
      { type: "p", text: "Because the data never leaves the user's device, there's no transfer or processing by a third party to account for - which makes client-side tools an easy choice for privacy-conscious individuals and teams." },
    ],
  },
  {
    slug: "compress-images-for-core-web-vitals",
    image: "/blog/compress-images-for-core-web-vitals.png",
    title: "Compress images for faster websites & better Core Web Vitals",
    description: "Images are usually the heaviest thing on a page. Here's how to compress them for great Largest Contentful Paint without hurting quality.",
    date: "2026-02-08",
    readMins: 6,
    tags: ["web", "performance"],
    relatedTools: ["compress-image", "webp-converter", "resize-image"],
    body: [
      { type: "p", text: "If your site feels slow, images are the first place to look. They're typically the largest assets on a page and the most common cause of a poor Largest Contentful Paint (LCP) score." },
      { type: "h2", text: "Right-size before you compress" },
      { type: "p", text: "Don't serve a 4000px photo into a 800px slot. Resize to the largest size it will actually be displayed at (account for high-DPI screens with roughly 2x), then compress." },
      { type: "h2", text: "Use a modern format" },
      { type: "p", text: "Converting JPGs to WebP or AVIF often cuts size by a third or more at the same quality. That directly improves load time and LCP." },
      { type: "h2", text: "Target a budget" },
      { type: "ul", items: [
        "Hero images: aim for under ~150-200 KB where possible.",
        "Thumbnails and inline images: often under 50 KB.",
        "Use exact-size targeting to keep every image within budget.",
      ] },
      { type: "h2", text: "Batch the whole folder" },
      { type: "p", text: "ShrinkTo can compress an entire batch at once and hand you a ZIP - useful for processing a whole gallery or content folder before deploying." },
    ],
  },
  {
    slug: "heic-to-jpg-convert-iphone-photos",
    image: "/blog/heic-to-jpg-convert-iphone-photos.png",
    title: "HEIC to JPG: convert iPhone photos for any platform",
    description: "HEIC keeps iPhone photos small, but not every app accepts it. Here's how to convert to universal JPG without uploading.",
    date: "2026-02-14",
    readMins: 4,
    tags: ["formats", "guide"],
    relatedTools: ["heic-to-jpg", "compress-image", "convert-image"],
    body: [
      { type: "p", text: "Apple's HEIC format saves space, but plenty of websites, forms, and Windows apps still don't accept it. Converting to JPG fixes compatibility instantly." },
      { type: "h2", text: "What is HEIC?" },
      { type: "p", text: "HEIC (High Efficiency Image Container) is the format iPhones use by default. It stores photos at roughly half the size of JPEG at similar quality - great for storage, less great for sharing outside Apple's ecosystem." },
      { type: "h2", text: "Convert in your browser" },
      { type: "ol", items: [
        "Open the HEIC to JPG tool.",
        "Drop in one or many HEIC files.",
        "Download the JPGs - or grab the whole batch as a ZIP.",
      ] },
      { type: "h2", text: "Bonus: compress at the same time" },
      { type: "p", text: "Since you're already re-encoding, you can hit a target size in the same step - handy for uploads with strict file-size limits." },
    ],
  },
  {
    slug: "best-ilovepdf-smallpdf-tinypng-alternatives-2026",
    image: "/blog/best-ilovepdf-smallpdf-tinypng-alternatives-2026.png",
    title: "Best free iLovePDF, Smallpdf & TinyPNG alternatives in 2026",
    description: "Looking for a private, unlimited, no-signup alternative to the big file tools? Here's what to look for - and a strong option.",
    date: "2026-02-20",
    readMins: 6,
    tags: ["comparison"],
    relatedTools: ["compress-image", "compress-pdf", "merge-pdf"],
    body: [
      { type: "p", text: "iLovePDF, Smallpdf and TinyPNG are popular for good reason, but they share three limitations: they upload your files to their servers, they cap free usage, and they often push you toward a paid plan. Here's what a better alternative looks like." },
      { type: "h2", text: "What to look for" },
      { type: "ul", items: [
        "Client-side processing - your files never leave your device.",
        "No daily limits or per-file size caps.",
        "No signup or email wall.",
        "Modern compression (MozJPEG, WebP, AVIF) and a full PDF toolset.",
        "Exact-size targeting, which most tools lack entirely.",
      ] },
      { type: "h2", text: "How ShrinkTo compares" },
      { type: "p", text: "ShrinkTo runs every non-AI tool entirely in your browser, so there's no upload and no usage limit. It matches iLovePDF's tool coverage (merge, split, convert, edit, protect) and aims to beat TinyPNG on compression by adding exact-KB targeting and AVIF output." },
      { type: "h2", text: "The trade-off" },
      { type: "p", text: "Client-side tools use your device's CPU, so very large batches take a moment locally rather than on a server farm. For the vast majority of tasks that's a non-issue - and the privacy and no-limits upside is well worth it." },
    ],
  },
];

export const POSTS_BY_SLUG: Record<string, BlogPost> = Object.fromEntries(
  POSTS.map((p) => [p.slug, p]),
);
